import type { ReactNode } from "react";

const SOURCE = {
  notes: "https://worldofwarcraft.blizzard.com/en-us/news/24293281/curse-of-ulatek-content-update-notes",
  coiledIsle: "https://worldofwarcraft.blizzard.com/en-us/news/24293963/follow-the-snakes-to-the-coiled-isle-for-new-adventures",
  prey: "https://worldofwarcraft.blizzard.com/en-gb/news/24262569/jagen-oder-gejagtwerden-mit-dem-beutejagdsystem-in-midnight",
  delves: "https://www.icy-veins.com/wow/delves-guide",
  vaults: "https://www.wowhead.com/guide/midnight/vaults-of-atalutek-patch-12-1-zone-activities-rewards-player-power",
  preyGuide: "https://www.wowhead.com/guide/midnight/prey-unlocking-hunts-rewards",
  mplus: "https://www.wowhead.com/guide/midnight/mythic-plus-season-overview",
  dungeons: "https://www.icy-veins.com/wow/dungeons-guide",
  folio: "https://worldofwarcraft.blizzard.com/news/24277442/updated-may-27-add-the-omnium-folio-to-your-library-of-tools-against-the-void",
  catalyst: "https://www.wowhead.com/guide/midnight/matrix-catalyst-crafting-tier-set",
} as const;

function Link({ href, children }: { href: string; children: ReactNode }) {
  return <a href={href} target="_blank" rel="noreferrer">{children} <span aria-hidden="true">↗</span></a>;
}

export function EndgameMechanicsAtlas() {
  return <>
    <section id="atlas" className="research-section">
      <p className="eyebrow">Start here · a map before a route</p>
      <h2>Every endgame system, sorted by what it actually is</h2>
      <p>Midnight does not have one “endgame.” It has several overlapping loops: content you play, systems that make you stronger, and systems that turn activity into loot. The names are unfortunately close enough to be confusing. This map separates them before asking you to optimise any of them.</p>
      <div className="research-callout"><strong>The four easy confusions:</strong> <em>Vaults of Atal’Utek</em> are the Coiled Isle’s outdoor public-event zone. A <em>Delve</em> is a short 1–5-player instance. The <em>Great Vault</em> is next week’s one-item reward menu. <em>Prey</em> is an outdoor hunting overlay. None is a renamed version of another.</div>
      <div className="research-table-wrap"><table className="research-table mechanics-table"><thead><tr><th>System</th><th>What it is</th><th>Why it exists</th><th>Cadence / social shape</th><th>Priority for a first 90</th></tr></thead><tbody>
        <tr><th>Campaign &amp; zone introductions</th><td>Story and access quests across Midnight, then Coiled Isle.</td><td>Unlocks places, vendors, world activities and Warband shortcuts.</td><td>One-time per character; some access is Warband-wide.</td><td>High: do once before judging the map.</td></tr>
        <tr><th>World quests, rares, renown &amp; assignments</th><td>Open-world objectives and faction progress.</td><td>Starter replacements, reputation rewards, materials and World-Vault credit.</td><td>Rotating / weekly; solo or casual ad-hoc groups.</td><td>Use to fill holes; do not mistake them for an endless mandatory grind.</td></tr>
        <tr><th>Coiled Isle &amp; its Vaults</th><td>A 12.1 outdoor zone and a separate public-event subzone.</td><td>12.1 story, outdoor catch-up gear, Mistcrests, Warband outdoor power.</td><td>Solo-friendly patrols; nearby-player Strikes, Incursions and bosses.</td><td>Do the introduction; then follow what you enjoy.</td></tr>
        <tr><th>Delves</th><td>Short scalable 1–5-player instances with Valeera.</td><td>A flexible solo/small-group gear and World-Vault lane.</td><td>Repeatable; Bountiful locations rotate daily.</td><td>Excellent if you want controlled, low-social-pressure progression.</td></tr>
        <tr><th>Prey</th><td>Opt-in outdoor hunt contracts layered onto zone play.</td><td>A second solo lane, rewards and World-Vault credit.</td><td>Repeatable; first two per difficulty weekly are the main gear rewards.</td><td>Try it for variety—never confuse it with a required daily quest.</td></tr>
        <tr><th>Normal / Heroic / M0 dungeons</th><td>Five-player scripted dungeons at increasingly structured difficulty.</td><td>Learn group encounters; M0 is a bridge to keys.</td><td>Normal/Heroic queue; M0 premade. Its current reset cadence needs live UI confirmation.</td><td>Heroic for queue comfort, M0 when ready to learn a full run.</td></tr>
        <tr><th>Mythic+</th><td>Repeatable timed five-player keystone dungeons.</td><td>Repeatable encounter loot, rating and Dungeon-Vault progression.</td><td>Premade only; unlimited runs, no ordinary instance lockout.</td><td>Optional. Enter through a learning +2–5, not pressure.</td></tr>
        <tr><th>LFR / raids / Lair</th><td>Large-group boss content; Tidebound Grotto is a one-boss Lair.</td><td>Raid loot, tier chances, social progression and Raid-Vault credit.</td><td>LFR queues; Normal/Heroic premades; fixed Mythic raid.</td><td>Choose for the encounters and people, not because every character must raid.</td></tr>
        <tr><th>Great Vault</th><td>Next reset’s menu of weekly activity offers.</td><td>Bad-luck protection / one higher-level choice.</td><td>Character-specific; unlock up to 9 offers, choose exactly 1.</td><td>Pick one comfortable row rather than forcing every row.</td></tr>
        <tr><th>Tracks, Mistcrests &amp; Catalyst</th><td>Item improvement and tier-set conversion systems.</td><td>Make strong drops last; turn eligible non-tier armour into tier.</td><td>Crests and Catalyst charges have weekly/catch-up rhythms.</td><td>Learn early; spend deliberately rather than immediately.</td></tr>
        <tr><th>Sparks, orders &amp; professions</th><td>Time-gated high-end crafts and specialised crafter progression.</td><td>Target a durable item, stats or embellishment.</td><td>Character Sparks; crafter expertise is separate.</td><td>Use an order when a planned piece is better than hoping for a slot drop.</td></tr>
        <tr><th>Omnium Folio</th><td>Expansion-long selectable player-power library, not gear.</td><td>Persistent Midnight power choices.</td><td>Unlock then progress through its own weekly knowledge path.</td><td>Start the unlock; finish at a comfortable pace.</td></tr>
      </tbody></table></div>
      <p className="research-footnote">There are also rotating world events, fishing/collection loops, PvP, older-release catch-up events and cosmetics. They can be worthwhile, but they are not secretly required steps in a Season 2 PvE gearing ladder. Patch notes replace old-event rewards as seasons move on; inspect the live tooltip before spending a week on an older event.</p>
      <Link href={SOURCE.notes}>Blizzard’s live 12.1 change list</Link>
    </section>

    <section id="solo-outdoor" className="research-section">
      <p className="eyebrow">Deep tutorial · solo &amp; outdoor lanes</p>
      <h2>Delves, Prey and Coiled Isle: three separate loops</h2>
      <p>If you only retain one thing from this guide, retain this: Delves are <strong>instances</strong>; Prey is a <strong>hunt overlay in the open world</strong>; Coiled Isle’s Vaults are <strong>public outdoor events</strong>. You may enjoy all three, but progress in one does not mean you have “done” the others.</p>

      <details className="mechanic-detail" open><summary><span>1</span> Delves: a first run, from door to reward</summary><div className="tutorial-body">
        <p><strong>What you are entering:</strong> a 10–20 minute scenario for one to five players. Valeera accompanies the group and can be configured as damage, healer or tank; she is a companion, not another player you must recruit. Set the tier at the entrance/Delver interface, go in, complete the scenario’s objective, and open the completion chest. Delves are repeatable and their tier unlocks are shared across Delves once earned.</p>
        <ol><li><strong>Start small.</strong> Run a normal T1–3 to learn the objective and Valeera controls. These are a rehearsal, not a test.</li><li><strong>At T4+, respect the shared revive budget.</strong> Releasing after death spends one; the current guide lists five shared revives at T4–8, then fewer at T9–11. A wipe is information—reduce tier, change Valeera’s role, or bring one friend.</li><li><strong>Separate normal from Bountiful.</strong> A Bountiful icon marks the day’s selected location. Finish it as normal, then use a Restored Coffer Key at its special end coffer for the Bountiful reward. A key on an unmarked Delve is not the same thing.</li><li><strong>Choose a sustainable tier.</strong> Direct normal completion rewards stop scaling meaningfully after T3; Bountiful/keyed rewards are the reason to climb. T8 is the practical direct-gear / World-Vault target. T9–11 are chiefly a higher challenge and crest-oriented progression, not a demand that every player must push them.</li><li><strong>Count three reward layers separately.</strong> The completion chest is now; the keyed Bountiful coffer is an optional now-reward; 2/4/8 qualifying activities can create World-Vault choices for next reset. Do not read a Vault number as the item you just received.</li></ol>
        <div className="research-callout"><strong>Good casual rule:</strong> spend a key only on a marked Bountiful Delve at a tier you expect to finish cleanly. A lower successful tier is more useful than consuming a key on a failed high tier. Exact shard/key acquisition amounts are still being adjusted in live 12.1 notes, so this site does not freeze a stale table.</div>
        <h4>What the Delve words mean</h4><dl className="tutorial-definitions"><dt>Bountiful</dt><dd>A daily rotating marked location with a special end coffer. It does not mean every Delve is Bountiful.</dd><dt>Restored Coffer Key</dt><dd>The consumable that opens the Bountiful coffer after a successful run.</dd><dt>Delver’s Journey</dt><dd>A seasonal Delve reward track. It is not the Prey track and not your Great Vault.</dd><dt>Undercoin / Voidlight Marl</dt><dd>Delve currencies for their relevant vendors/systems. Neither is a Coiled Isle Corrosive Coin.</dd><dt>Nemesis</dt><dd>An optional seasonal Delve encounter/reward pursuit, separate from normal completion.</dd><dt>Curios</dt><dd>Valeera customisation choices; read the actual effect and use the ones that solve your current run.</dd></dl>
        <Link href={SOURCE.delves}>Current Delve tiers, revives and reward layers</Link>
      </div></details>

      <details className="mechanic-detail"><summary><span>2</span> Prey: an outdoor hunt, not a world quest</summary><div className="tutorial-body">
        <p><strong>First unlock:</strong> at level 90, take Astalor Bloodsworn’s Silvermoon introduction and use the Hunt Table. Choose a target and difficulty. The Anguish crystal interface then follows you while you play in the relevant outdoor zone. Do marked activities—such as objectives, treasures, rares, remnants, traps and ambushes—until the target’s location is revealed; activate the crystal and defeat the target.</p>
        <ol><li><strong>Choose Normal first.</strong> It teaches tracking and ambushes. If an ambush occurs, control the encounter rather than assuming you failed the hunt.</li><li><strong>Hard and Nightmare add Torments.</strong> They are deliberate difficulty modifiers, not an item-level requirement you should grind through blindly. Learn the specific Torment before treating Nightmare as routine content.</li><li><strong>Understand the weekly reward limit.</strong> The first two completed hunts on <em>each difficulty</em> are the key direct gear rewards. Later hunts can still progress systems/currencies, but they are not an infinite direct-gear farm.</li><li><strong>Use it as a World-Vault lane.</strong> Prey can fill World-Vault activity slots. Nightmare can reach the World-row ceiling, but this is still next week’s single choice, not an instant guarantee.</li></ol>
        <p><strong>12.1 extension:</strong> after the relevant campaign step, Coiled Isle adds <em>A Slithering Threat</em>, Nightmare-hunt Relics and the Curse of the Isle toggle. The toggle changes the outdoor rules and lets players contribute Ossified Relics at a Haunted Brazier to summon Ral’kala. This is cooperative outdoor challenge content, not a Delve boss and not the Corrosive Coin system.</p>
        <div className="research-callout"><strong>Do not mix the two seasonal tracks:</strong> <em>Preyhunter Journey</em> is Prey’s ten-rank track (including Soul rewards at later ranks); <em>Delver’s Journey</em> is the Delve track. Their names and rewards overlap enough that the in-game track label matters.</div>
        <Link href={SOURCE.prey}>Blizzard’s Prey system introduction</Link> <span aria-hidden="true"> · </span><Link href={SOURCE.preyGuide}>Current 12.1 Prey unlocking and rewards</Link>
      </div></details>

      <details className="mechanic-detail"><summary><span>3</span> Coiled Isle Vaults: public events and outdoor power</summary><div className="tutorial-body">
        <p><strong>First unlock:</strong> continue the 12.1 campaign through <em>Into the Vaults of Atal’Utek</em>. This access is reported as Warband-wide once unlocked. The Vaults are a hostile outdoor subzone: you can see other players and spontaneously help one another, but you are not in a dungeon instance or a Great Vault screen.</p>
        <p>The activity chain is broadly <strong>Patrol → Strike → Incursion → Ancient Foe</strong>. Patrols are quick solo objectives; Strikes are tougher two-stage elite tasks; Incursions and Ancient Foes invite nearby-player cooperation. The weekly <em>Purging the Vaults</em> asks you to complete the chain’s major forms once. That makes this an approachable place to practise informal social play: join the marked fight, follow the objective, and leave when done.</p>
        <h4>Three currencies with deliberately different jobs</h4><dl className="tutorial-definitions"><dt>Corrosive Coin</dt><dd>Earned in the Vaults and spent into the Altar of Corrosion’s zone-oriented trait tree.</dd><dt>Spirit Corrosion</dt><dd>The points used to select Altar traits. Treat those traits as Coiled Isle/Vault power unless the current in-game tooltip explicitly says otherwise.</dd><dt>Corrosive Soul</dt><dd>Feeds the Corrosive Codex’s permanent Gifts. These are the broader Warband outdoor/Delve benefits—not the same thing as the Altar tree.</dd><dt>Ossified Relic</dt><dd>Prey’s Coiled Isle contribution currency for the Haunted Brazier/Ral’kala loop.</dd></dl>
        <p><strong>Important source correction:</strong> a pre-season guide says Altar enhancements work in Delves; the newer Vault guide distinguishes Altar traits from Codex Gifts and limits the former to the Coiled Isle/Vault context. Blizzard’s notes do not settle this. Treat the current in-game trait tooltip as decisive; this guide will not promise Delve power from an outdoor trait.</p>
        <p>Curse Surges (currently shortened to a 30-minute cadence by hotfix) are rotating outdoor waves with rare elites and fishing/collection links. They are a flavourful optional loop, not a baseline gearing chore. Tidebound Grotto is different again: a one-boss scalable <em>Lair</em>, closer to a small flexible raid/world-boss evolution than a Delve.</p>
        <Link href={SOURCE.coiledIsle}>Blizzard’s Coiled Isle overview</Link> <span aria-hidden="true"> · </span><Link href={SOURCE.vaults}>Vaults, Codex and event-chain reference</Link>
      </div></details>

      <details className="mechanic-detail"><summary><span>4</span> “What should I do tonight?” without turning it into chores</summary><div className="tutorial-body">
        <div className="research-table-wrap"><table className="research-table"><thead><tr><th>If you want…</th><th>Choose…</th><th>Stop when…</th></tr></thead><tbody>
          <tr><th>Quiet repeatable combat</th><td>A normal or Bountiful Delve at a safe tier.</td><td>You have your desired World-Vault slots or no longer enjoy the run.</td></tr>
          <tr><th>Outdoor variety and a hunt target</th><td>One Prey contract, starting Normal.</td><td>You have completed the two weekly gear hunts for that difficulty, unless you want its other rewards.</td></tr>
          <tr><th>Low-commitment public cooperation</th><td>Vault Patrols/Strikes or a visible Incursion/Ancient Foe.</td><td>The weekly chain is done or the event stops being fun.</td></tr>
          <tr><th>12.1 outdoor power</th><td>Campaign, a few Vault events, then choose Codex Gifts you actually value.</td><td>You have a useful Gift direction; do not turn spare Souls into a reflex purchase.</td></tr>
          <tr><th>A conventional group dungeon</th><td>Heroic queue or a premade M0.</td><td>You have learned the dungeon or earned the reward you wanted.</td></tr>
        </tbody></table></div>
      </div></details>
    </section>

    <section id="instance-doors" className="research-section">
      <p className="eyebrow">Deep tutorial · choose the right group door</p>
      <h2>Normal, Heroic, Mythic 0, Mythic+, raids and Lairs</h2>
      <div className="research-grid research-grid-2"><div><h3>“I want the game to make the group”</h3><p>Normal and Heroic dungeons, and LFR raid wings, are queueable. They are the least demanding way to see group content, but queueable does not mean every later activity has a queue.</p></div><div><h3>“I want to choose the group”</h3><p>M0, Mythic+, Normal/Heroic raid and Lair difficulties use Premade Groups, a guild/community or friends. That is a social filter, not a skill exam: make a listing that says <em>learning / completion / no voice</em> when that is your goal.</p></div></div>
      <div className="research-table-wrap"><table className="research-table"><thead><tr><th>Door</th><th>What changes</th><th>Queue / lockout</th><th>Use it for</th></tr></thead><tbody>
        <tr><th>Normal</th><td>Introductory five-player dungeon.</td><td>Queueable.</td><td>Story and first exposure, not durable 90 gear.</td></tr>
        <tr><th>Heroic</th><td>Level-90 seasonal five-player version.</td><td>Queueable; counts for Dungeon Vault.</td><td>Low-pressure group mechanics and early replacements.</td></tr>
        <tr><th>Mythic 0 (M0)</th><td>Untimed maximum base dungeon, no keystone.</td><td>Premade; reset cadence is currently disputed by guides, so inspect the live Instance Info panel.</td><td>The best no-timer bridge before keys.</td></tr>
        <tr><th>Mythic+</th><td>Keystone, timer, Enemy Forces, scaling modifiers.</td><td>Premade; repeatable and always loot-eligible.</td><td>Repeatable five-player progression and Dungeon Vault.</td></tr>
        <tr><th>LFR / raid</th><td>Boss-focused large-group difficulties.</td><td>LFR queues; higher difficulties premade.</td><td>Story, tier chances, organised encounter progression.</td></tr>
        <tr><th>Lair</th><td>One-boss scalable group encounter (Tidebound Grotto).</td><td>Separate summoning stone; not a dungeon or Delve.</td><td>A compact world-boss/raid-like encounter.</td></tr>
      </tbody></table></div>
      <details className="mechanic-detail"><summary><span>+</span> Mythic+ from the first keystone onward</summary><div className="tutorial-body"><p>A keystone names a dungeon and a level. A party of five travels to that dungeon, puts the key into the Font of Power, then kills every boss and enough non-boss enemies to fill Enemy Forces before the timer. The key owner’s key changes after completion; everyone receives the run’s credit and end reward. There is no automatic backfill once started, so agree on the goal before the first pull.</p><p>Keys come from an M0 final boss, completing another player’s M+, selecting the Vault after an earlier M+ week, or a T11 Delve. A new key begins at +2. At +2–5, Lindormi’s Guidance marks a learning route, weakens marked non-boss packs and removes death timer loss. At +6–11 deaths cost five seconds; at +12+ they cost fifteen seconds (until the final minute). The current low-key boundary is +2–5—not an older guide’s +2–4.</p><p><strong>Practical social start:</strong> host your own +2 titled <code>learning · completion · returning player · no voice</code>. Invite a tank and healer first, say hello before the key, ask whether the group wants to finish if the timer is lost, and treat survival/interrupts as the first job. A late finish still has loot/Vault value; timing changes the key and rating outcome.</p><p><strong>Reward boundary:</strong> end-of-dungeon M+ gear caps at Hero 3; a +10 earns a following-week Myth 1 Dungeon-Vault bracket, not instant Myth loot. The timer is part of the activity, not a reason to abandon respectful learners. Repeated improper departures can earn a Keystone Deserter flag.</p><Link href={SOURCE.mplus}>Current M+ mechanics, reward table and modifiers</Link> <span aria-hidden="true"> · </span><Link href={SOURCE.dungeons}>Dungeon difficulties and Season 2 pool</Link></div></details>
    </section>

    <section id="power-systems" className="research-section">
      <p className="eyebrow">Deep tutorial · systems that act on your loot</p>
      <h2>Upgrades, tier, bonus rolls, Folio and old-content catch-up</h2>
      <div className="research-grid research-grid-3"><div><h3>Upgrade tracks</h3><p>Five overlapping six-rank tracks use their matching Mistcrests and gold. A track is a ceiling and a spending language, not a verdict that a lower-track set piece is worthless.</p></div><div><h3>Matrix Catalyst</h3><p>Turns an eligible Veteran-track-or-higher armour item into tier. Use charges for one of the five set slots when it completes or moves you toward a meaningful set bonus; crafted armour is ineligible.</p></div><div><h3>Nebulous Voidcore</h3><p>A Vault alternate choice after enough Vault offers. It is a targeted bonus-roll opportunity, not a free extra Vault item; choosing it can mean declining a real upgrade.</p></div></div>
      <div className="research-callout"><strong>Omnium Folio is neither a trinket nor gear:</strong> begin its unlock through the Magister’s Missive / <em>The Magisters’ Call</em>. It gives expansion-long selectable power choices after weekly knowledge progress. It belongs on a first-character checklist, but it does not consume an equipment slot.</div>
      <details className="mechanic-detail"><summary><span>!</span> Legacy and catch-up activities: useful, but read the season label</summary><div className="tutorial-body"><p>Void Assaults, Void Incursions, Field Accolades, Ritual Sites, Showdown areas and earlier world-boss rewards can still appear on the map or in guides. Their job is catch-up, outdoor variety or collections. Blizzard’s 12.1 notes explicitly replace/retune several of their rewards for Season 2; some old Season 1 rewards are non-upgradeable. Do not plan a current gear route from a guide that silently calls an old reward “Myth” without checking the item’s live Season 2 track.</p><p>Field Accolade caches are a readable example of the current catch-up role: 200 buys Warbound Adventurer gear, 500 a random Veteran piece, and 750 a targeted Veteran piece. That is helpful for a fresh alt or bad slot—not a substitute for current Hero/Myth progression. Void Strikes, Incursions and their weekly continue to grant Season 2 Adventurer crests.</p></div></details>
      <Link href={SOURCE.folio}>Blizzard’s Omnium Folio introduction</Link> <span aria-hidden="true"> · </span><Link href={SOURCE.catalyst}>Current Matrix Catalyst eligibility and charges</Link> <span aria-hidden="true"> · </span><Link href={SOURCE.notes}>Season 2 catch-up replacement details</Link>
    </section>
  </>;
}
