import type { ErpPortfolioFulfillmentReview, ErpSavedNeedHistory, ErpSourceFulfillmentReview } from "@wowsync-dashboard/core";
import { erpNeedAnchorId, erpSavedNeedHistoryAnchorId, erpSourceFulfillmentAnchorId, erpWorkOrderAnchorId } from "./erpObservationChangeQueue.ts";

function prerequisiteGateLabel(state: ErpPortfolioFulfillmentReview["packages"][number]["steps"][number]["prerequisiteGate"]["state"]): string {
  switch (state) {
    case "NO_PREREQUISITES": return "No prerequisite evidence gate is linked.";
    case "CURRENT_OBSERVED_EVIDENCE_MET": return "All linked prerequisite needs have recent timestamped observed coverage. This satisfies the evidence gate only; it does not prove a manual action was completed.";
    case "PREREQUISITE_EVIDENCE_REVIEW": return "A linked prerequisite is stale, partial, unknown, short, or encumbered by competing reservations. Review upstream evidence and commitments before relying on this step.";
    case "MISSING_PREREQUISITE": return "A saved prerequisite reference is unavailable. Its evidence is UNKNOWN and the link needs repair.";
    case "CYCLE_REVIEW": return "The package contains a cycle. Review its saved links before using the sequence.";
  }
}

/** Shows only player-authored dependency chains and their shared evidence/readiness projection. */
function nextReviewLabel(state: ErpSourceFulfillmentReview["sources"][number]["nextReview"]): string {
  switch (state) {
    case "REVIEW_EVIDENCE": return "Review missing or stale evidence";
    case "REVIEW_RESERVATIONS": return "Review reservations";
    case "RECONCILE_OBSERVATIONS": return "Reconcile changed observations";
    case "PLAN_MANUAL_WORK": return "Plan a manual task";
    case "REVIEW_MANUAL_WORK": return "Review blocked manual work";
    case "REVIEW_SOURCE_AND_ACCESS": return "Review source and access";
  }
}

function savedBatchReviewNeeds(batch: ErpPortfolioFulfillmentReview["savedPlanningBatches"][number]): { readonly projectId: string; readonly needId: string }[] {
  return [...new Map(batch.steps.filter((step) => step.evidenceReview !== "NO_NEWER_OBSERVATION" && step.evidenceReview !== "NEED_IDENTITY_CHANGED" && (step.workOrderStatus === "COMPLETED" || step.workOrderStatus === "CANCELLED")).map((step) => [`${step.projectId}\u0000${step.needId}`, { projectId: step.projectId, needId: step.needId }] as const)).values()];
}

function requirementReviewBlocker(batch: ErpPortfolioFulfillmentReview["savedPlanningBatches"][number] | undefined, projectId: string, needId: string): string | undefined {
  if (!batch) return "The saved generation is outside the returned batch history window.";
  if (batch.lineageState === "FOLLOW_UP_CONTEXT_CONFLICT" || batch.state === "CONFLICTING_BATCH_CONTEXT") return "This generation has conflicting saved context; resolve the conflict before branching from it.";
  const steps = batch.steps.filter((step) => step.projectId === projectId && step.needId === needId);
  if (!steps.length) return "This generation has no saved task for this exact requirement.";
  if (steps.some((step) => step.workOrderStatus !== "COMPLETED" && step.workOrderStatus !== "CANCELLED")) return "An earlier manual task is still open; review or close it before creating another instruction.";
  if (steps.some((step) => step.evidenceReview === "NEED_IDENTITY_CHANGED")) return "The requirement identity changed since this generation was saved.";
  if (!steps.some((step) => step.evidenceReview !== "NO_NEWER_OBSERVATION")) return "No newer observation is available for this saved review yet.";
  return undefined;
}

/** Shows portfolio dependency packages alongside needs grouped by an explicitly declared source/resource scope. */
export function ErpPortfolioFulfillmentPanel({ review, sourceReview, characterName, busy = false, onPlanSourceLeadBatch, onPlanNeed, onPlanBatchNeeds, onPlanHistoryEntry }: { review: ErpPortfolioFulfillmentReview; sourceReview: ErpSourceFulfillmentReview; characterName: (identityKey?: string) => string; busy?: boolean; onPlanSourceLeadBatch?: (source: ErpSourceFulfillmentReview["sources"][number], lead: ErpSourceFulfillmentReview["sources"][number]["alternativeLocations"][number], mode: "INVESTIGATE" | "PROVISION") => void; onPlanNeed?: (projectId: string, needId: string, pathwayKind: ErpSourceFulfillmentReview["sources"][number]["needs"][number]["fulfillmentPathways"]["options"][number]["kind"]) => void; onPlanBatchNeeds?: (batchId: string, needs: readonly { readonly projectId: string; readonly needId: string }[]) => void; onPlanHistoryEntry?: (history: ErpSavedNeedHistory, entry: ErpSavedNeedHistory["entries"][number]) => void }) {
  return <section className="erp-portfolio-fulfillment" aria-labelledby="erp-portfolio-fulfillment-title" data-testid="erp-portfolio-fulfillment">
    <h2 id="erp-portfolio-fulfillment-title">Portfolio fulfillment review</h2>
    <section aria-labelledby="erp-source-fulfillment-title" data-testid="erp-source-fulfillment">
      <h3 id="erp-source-fulfillment-title">Shared source and resource review</h3>
      <p>{sourceReview.openProvisioningPlanCount} open provisioning work order{sourceReview.openProvisioningPlanCount === 1 ? "" : "s"} across active and paused projects. These are player-authored plans, not reservations, current stock, or proof of movement.</p>
      <p>These rows join active and paused requirements that explicitly select the same source and exact resource identity, with each need&apos;s evidence, reservations, and linked task observations. This is not a route or availability calculation.</p>
      <p>{sourceReview.totalSourceCount} source/resource groups Â· {sourceReview.totalNeedCount} needs Â· {sourceReview.needsReviewCount} groups have a next review step.</p>
      {!sourceReview.sources.length ? <p>No active or paused needs explicitly select a source for this version.</p> : <ol>{sourceReview.sources.map((source) => <li id={erpSourceFulfillmentAnchorId(source.stableId)} key={source.stableId} data-testid={`erp-source-fulfillment-${encodeURIComponent(source.stableId)}`} tabIndex={-1}>
        <h4>{source.sourceIdentityKey ? characterName(source.sourceIdentityKey) : `Shared owner ${source.sourceOwnerKey}`} Â· {source.label} (<code>{source.resourceKey}</code>) Â· {source.kind}</h4>
        <p><strong>Next review:</strong> {nextReviewLabel(source.nextReview)}. {source.reason}</p>
        <section aria-label="Other observed locations for this resource">
          <h5>Other observed location leads Â· {source.alternativeLocationReview.replaceAll("_", " ")}</h5>
          {source.alternativeLocations.length ? <ul>{source.alternativeLocations.map((location, index) => <li key={`${location.sourceIdentityKey}:${location.observedAt ?? "unknown"}:${index}`}>
            <strong>{location.sourceName}{location.sourceSurname ? ` ${location.sourceSurname}` : ""} Â· {location.sourceRealm}</strong> Â· {location.state} Â· {location.freshness}{location.observedAt !== undefined ? ` Â· seen ${new Date(location.observedAt * 1000).toLocaleString()}` : " Â· time UNKNOWN"}{location.observedQuantity !== undefined ? ` Â· ${location.observedQuantity} observed` : " Â· current quantity UNKNOWN"}{location.potentialQuantity !== undefined ? ` Â· ${location.potentialQuantity} LAST_SEEN` : ""}{location.availableObservedLowerBound !== undefined ? ` Â· at least ${location.availableObservedLowerBound} below recorded reservations` : " Â· available quantity UNKNOWN"}
            <ul>{location.matchingItems.map((item, itemIndex) => <li key={`${item.itemRef}:${item.section}:${itemIndex}`}><code>{item.itemRef}</code> Â· {item.section} Â· {item.state}{item.quantity !== undefined ? ` Â· ${item.quantity} units` : " Â· quantity UNKNOWN"}</li>)}</ul>
            <p>Membership: {location.accountMembership} Â· access: {location.access} Â· transferability: {location.transferability}. {location.reason}</p>
            {location.needReferences.map((reference) => <a key={`${reference.projectId}:${reference.needId}`} href={`#${erpNeedAnchorId(reference.projectId, reference.needId)}`}>Review location evidence for {reference.projectTitle}</a>)}
            {location.selectedProvisioningPlanCount > 0 && <section aria-label={`Existing plans selecting ${location.sourceName} as a source`}><strong>{location.selectedProvisioningPlanCount} open player-authored provisioning plan use{location.selectedProvisioningPlanCount === 1 ? "" : "s"} select this character as source</strong><ul>{location.selectedProvisioningPlans.map((plan) => <li key={`${plan.projectId}:${plan.workOrderId}:${plan.needId}`}><a href={`#${erpWorkOrderAnchorId(plan.projectId, plan.workOrderId)}`}>{plan.projectTitle}: {plan.workOrderTitle}</a> · {plan.workOrderStatus.replaceAll("_", " ")} · intended recipient {characterName(plan.destinationIdentityKey)}{plan.reconciliationState ? ` · observation review ${plan.reconciliationState.replaceAll("_", " ")}` : " · observation reconciliation unavailable"}. This is a saved plan, not a reservation or evidence of movement.</li>)}</ul>{location.selectedProvisioningPlansTruncated && <small>Showing 25 of {location.selectedProvisioningPlanCount} selected plans.</small>}</section>}
            {location.needReferences.length >= 2 && onPlanSourceLeadBatch && <><button type="button" disabled={busy} onClick={() => onPlanSourceLeadBatch(source, location, "INVESTIGATE")}>Create linked investigation reviews</button><small>Creates one revision-checked, player-authored INVESTIGATE work order for each currently eligible linked requirement. It checks the location lead only; ownership, access, transferability, and movement remain UNKNOWN.</small>{source.kind === "ITEM_REF" && location.state === "OBSERVED" && location.freshness === "recent" && location.reservationState === "UNRESERVED" && location.activeReservationQuantity === 0 && (location.availableObservedLowerBound ?? 0) > 0 && location.matchingItems.some((item) => item.itemRef === source.resourceKey && item.state === "OBSERVED" && (item.quantity ?? item.knownLowerBound ?? 0) > 0) && <><button type="button" disabled={busy} onClick={() => onPlanSourceLeadBatch(source, location, "PROVISION")}>Create linked manual provisioning reviews</button><small>Available only for a recent, unreserved observation of this exact itemString. This creates player instructions; ownership, recipient access, transferability, and route remain UNKNOWN. Nothing is moved.</small></>}</>}
          </li>)}</ul> : <p>{source.alternativeLocationReview === "NO_MATCHING_LOCATION_OBSERVED" ? "The scanned same-version characters showed no matching alternative location." : source.alternativeLocationReview === "NO_OTHER_CHARACTERS_TO_SCAN" ? "No other same-version character was available to scan for this review. Other characters or locations may exist and are UNKNOWN." : source.alternativeLocationReview === "SOURCE_REVIEW_UNAVAILABLE" ? "Location review is unavailable for at least one linked need. This does not mean storage is empty." : "Potential locations are unavailable or the character scan was incomplete. This does not mean storage is empty."}</p>}
          {source.alternativeLocationsTruncated && <p role="note">Showing 25 of {source.alternativeLocationCount} location evidence rows.</p>}
          {source.alternativeLocationReview === "POTENTIAL_LOCATIONS_SCAN_INCOMPLETE" && <p role="note">Some potential locations were observed, but the character scan is incomplete. The displayed leads are not a complete list.</p>}
          <small>These rows are location leads. They do not establish account membership, access, ownership, transferability, or a retrieval route.</small>
        </section>
        <ul>{source.needs.map((need) => <li key={`${need.projectId}:${need.needId}`}>
          <strong>{need.projectTitle}</strong> Â· {need.projectStatus} Â· priority {need.projectPriority} Â· requires {need.requiredQuantity} Â· {need.state.replaceAll("_", " ")} Â· {need.freshness}{need.observedQuantity !== undefined ? ` Â· ${need.observedQuantity} OBSERVED` : " Â· current quantity UNKNOWN"}{need.potentialQuantity !== undefined ? ` Â· ${need.potentialQuantity} LAST_SEEN` : ""}{need.observedAt !== undefined ? ` Â· ${new Date(need.observedAt * 1000).toLocaleString()}` : " Â· timestamp UNKNOWN"}
          <p>Destination: {characterName(need.destinationIdentityKey)}. Sections: {need.sourceSections.length ? need.sourceSections.map((section) => `${section.section} ${section.state}${section.completeness ? ` (${section.completeness})` : ""}${section.observedAt !== undefined ? ` at ${new Date(section.observedAt * 1000).toLocaleString()}` : ""}`).join("; ") : "UNKNOWN"}. Reservations: {need.reservationAssessment ? `${need.reservationAssessment.activeQuantity} Â· ${need.reservationAssessment.state.replaceAll("_", " ")}` : "UNKNOWN"}. {need.unresolvedSections.length ? `Unresolved: ${need.unresolvedSections.join(", ")}. ` : ""}{need.reason}</p>
          <section aria-label={"Evidence-supported fulfillment options for " + need.label} data-testid={"erp-fulfillment-pathways-" + need.projectId + "-" + need.needId}>
            <h6>Evidence-supported review options: {need.fulfillmentPathways.state.replaceAll("_", " ")}</h6>
            <p>{need.fulfillmentPathways.reason}</p>
            {need.fulfillmentPathways.options.length ? <ul>{need.fulfillmentPathways.options.map((option, index) => <li key={option.kind + ":" + index}><strong>{option.kind.replaceAll("_", " ")}</strong>{option.observedLocation && <>; {option.observedLocation.section}: {option.observedLocation.quantity} observed{option.observedLocation.observedAt ? " at " + new Date(option.observedLocation.observedAt * 1000).toLocaleString() : ""}{option.observedLocation.itemRef ? <>; <code>{option.observedLocation.itemRef}</code></> : ""}</>}{option.candidateLocations?.length ? <>; location leads: {option.candidateLocations.map((location) => <span key={location.characterKey}>{location.characterName} ({location.realm}) · {location.provenance}, {location.freshness}{location.observedAt !== undefined ? `, seen ${new Date(location.observedAt * 1000).toLocaleString()}` : ", timestamp UNKNOWN"}; </span>)}</> : ""}{option.workOrderIds?.length ? <>; linked work: {option.workOrderIds.map((id, index) => <span key={id}>{index > 0 ? ", " : ""}<a href={"#" + erpWorkOrderAnchorId(need.projectId, id)}>{id}</a></span>)}</> : ""}. {option.reason}</li>)}</ul> : <p>No pathway can be supported from the recorded evidence.</p>}
            <small>These are evidence-qualified review options, not a ranked or executable plan. The player chooses the next step; unknown ownership, access, route, recipe, price, and action cause remain unknown.</small>
            {onPlanNeed && need.projectStatus === "ACTIVE" && !need.workOrders.length && need.fulfillmentPathways.options.some((option) => ["REVIEW_PERSONAL_BANK_RETRIEVAL", "INVESTIGATE_OTHER_CHARACTER_LOCATION", "CHOOSE_MANUAL_SUPPLY_PLAN", "REFRESH_OR_CLARIFY_EVIDENCE"].includes(option.kind)) && <ul aria-label={`Plan from an evidence pathway for ${need.label}`}>{need.fulfillmentPathways.options.filter((option) => ["REVIEW_PERSONAL_BANK_RETRIEVAL", "INVESTIGATE_OTHER_CHARACTER_LOCATION", "CHOOSE_MANUAL_SUPPLY_PLAN", "REFRESH_OR_CLARIFY_EVIDENCE"].includes(option.kind)).map((option) => <li key={option.kind}><button type="button" disabled={busy} onClick={() => onPlanNeed(need.projectId, need.needId, option.kind)}>Plan manual review from {option.kind.replaceAll("_", " ").toLowerCase()}</button></li>)}</ul>}
          </section>
          {need.workOrders.length ? <ul aria-label={`Linked work for ${need.label}`}>{need.workOrders.map((order) => <li key={order.stableId}>{order.kind} Â· recorded status {order.status.replaceAll("_", " ")} Â· readiness {order.readinessState?.replaceAll("_", " ") ?? "UNKNOWN"}{order.progressState ? ` Â· progress ${order.progressState.replaceAll("_", " ")}` : ""}{order.observationStates.length ? ` Â· paired evidence ${order.observationStates.join(", ")}` : " Â· no comparable paired observation"}{order.capabilityChecks.length ? ` Â· capability evidence ${order.capabilityChecks.map((check) => `${check.kind} ${check.state}`).join(", ")}` : ""}{order.plannedOutputState ? ` Â· planned output observation ${order.plannedOutputState}` : ""}{order.procurement ? ` Â· purchase ${order.procurement.reviewState}, quote ${order.procurement.quoteState}${order.procurement.quote ? ` (${order.procurement.quote.amountCopper} copper for ${order.procurement.quote.quantity}, ${order.procurement.quote.freshness})` : ""}; market availability and affordability UNKNOWN` : ""}: {order.title}. {order.reason ?? ""}</li>)}</ul> : <p>No linked manual task is recorded for this need.</p>}
          {need.workOrders.filter((order) => order.pathwayContext).map((order) => <p key={`${order.stableId}:pathway`}><strong>Pathway reviewed when planned:</strong> {order.pathwayContext!.kind.replaceAll("_", " ")} · {order.pathwayContext!.provenance}, {new Date(order.pathwayContext!.reviewedAt * 1000).toLocaleString()}. {order.pathwayContext!.reason} This is historical decision context; check current evidence before acting.</p>)}
          <a href={`#${erpNeedAnchorId(need.projectId, need.needId)}`}>Open requirement, evidence, and manual task controls</a>
        </li>)}</ul>
        <p>Source scope is explicit player intent. It does not establish ownership, accessibility, a transfer/crafting/purchase route, or task completion.</p>
      </li>)}</ol>}
      {sourceReview.truncated && <p role="note">Showing {sourceReview.returnedSourceCount} of {sourceReview.totalSourceCount} source/resource groups; this review is incomplete.</p>}
      <small>Changed quantities and paired observations preserve cause UNKNOWN. Reservations remain commitments, not proof of possession.</small>
    </section>
    <h3>Saved planning batches</h3>
    <p>These are atomic player-authored batches already saved across projects. Later observations are compared with the evidence recorded at confirmation; a quantity change does not prove that a planned action caused it.</p>
    <p>{review.totalSavedPlanningBatchCount} saved batch{review.totalSavedPlanningBatchCount === 1 ? "" : "es"} · {review.savedPlanningBatches.reduce((sum, batch) => sum + batch.steps.length, 0)} returned steps.</p>
    {!review.savedPlanningBatches.length ? <p>No grouped planning batches have been saved for this version.</p> : <ol data-testid="erp-saved-planning-batches">{review.savedPlanningBatches.map((batch) => <li key={batch.stableId} data-testid={`erp-saved-batch-${encodeURIComponent(batch.stableId)}`}>
      <h4>Saved batch · {batch.state.replaceAll("_", " ")} · reviewed {new Date(batch.reviewedAt * 1000).toLocaleString()}</h4>
      <p>{batch.openTaskCount} open manual task{batch.openTaskCount === 1 ? "" : "s"} · {batch.terminalTaskCount} terminal task{batch.terminalTaskCount === 1 ? "" : "s"} · {batch.newerObservationReviewCount} newer evidence row{batch.newerObservationReviewCount === 1 ? "" : "s"} to inspect.</p>
      {savedBatchReviewNeeds(batch).length > 0 && onPlanBatchNeeds && <button type="button" disabled={busy} onClick={() => onPlanBatchNeeds(batch.stableId, savedBatchReviewNeeds(batch))}>Review {savedBatchReviewNeeds(batch).length} affected requirement{savedBatchReviewNeeds(batch).length === 1 ? "" : "s"} in grouped planner</button>}
      {batch.replanFrom && <p>Follow-up of saved batch <code>{batch.replanFrom.batchId}</code> · {batch.replanFrom.needReferences.length} exact reviewed requirement{batch.replanFrom.needReferences.length === 1 ? "" : "s"}. Lineage: {batch.lineageState.replaceAll("_", " ")}.</p>}
      {batch.followUpBatchIds.length > 0 && <p>This saved plan has {batch.followUpBatchIds.length} recorded follow-up plan{batch.followUpBatchIds.length === 1 ? "" : "s"}: {batch.followUpBatchIds.map((id) => <code key={id}>{id} </code>)} Lineage records planning context only; it does not establish that work happened.</p>}
      <ul>{batch.steps.map((step) => <li key={`${step.projectId}:${step.workOrderId}`}>
        <a href={`#${erpWorkOrderAnchorId(step.projectId, step.workOrderId)}`}>{step.projectTitle}: {step.workOrderTitle}</a> · {step.workOrderStatus.replaceAll("_", " ")} · {step.workOrderKind.replaceAll("_", " ")} · <code>{step.resourceKey}</code>
        <p>Evidence review: {step.evidenceReview.replaceAll("_", " ")} · current {step.currentEvidenceState.replaceAll("_", " ")}, {step.currentFreshness} freshness{step.currentQuantity !== undefined ? ` · ${step.currentQuantity} observed` : " · quantity UNKNOWN"}{step.currentObservedAt !== undefined ? ` · seen ${new Date(step.currentObservedAt * 1000).toLocaleString()}` : " · timestamp UNKNOWN"}{step.reviewedQuantity !== undefined ? ` · at review ${step.reviewedQuantity}` : " · review quantity UNKNOWN"} · active reservation intent {step.activeReservationQuantity}. Action cause: UNKNOWN.</p>
      </li>)}</ul>
    </li>)}</ol>}
    {review.savedPlanningBatchesTruncated && <p role="note">Saved planning batches are capped; narrow the version's project list to inspect the full history.</p>}
    <h3>Requirement history across saved plans</h3>
    <p>Follow one exact project requirement through its saved planning batches. Evidence at each review and current evidence are shown separately; this history does not prove that a planned action caused a resource change.</p>
    {!review.savedNeedHistories.length ? <p>No saved plan history is available for a requirement in this version.</p> : <ol data-testid="erp-saved-need-histories">{review.savedNeedHistories.map((history) => <li id={erpSavedNeedHistoryAnchorId(history.projectId, history.needId)} key={history.stableId} data-testid={`erp-saved-need-history-${encodeURIComponent(history.projectId)}-${encodeURIComponent(history.needId)}`}>
      <h4>{history.projectTitle}: {history.needLabel}</h4>
      <p>Requirement <code>{history.projectId}/{history.needId}</code> · current resource <code>{history.resourceKey}</code> · historical resource identities {history.reviewedResourceKeys.map((key) => <code key={key}>{key} </code>)} · identity {history.identityState.replaceAll("_", " ")} · next review {history.nextReview === "REVIEW_INTERVENING_EVIDENCE" ? "REVIEW INTERVENING RESOURCE EVIDENCE" : history.nextReview.replaceAll("_", " ")}. {history.nextReview === "REVIEW_INTERVENING_EVIDENCE" && <a href={`#${erpNeedAnchorId(history.projectId, history.needId)}`}>Open this requirement to reconcile its observed interval</a>}</p>
      <ol>{history.entries.map((entry) => <li key={entry.batchId}>
        <strong>Reviewed {new Date(entry.reviewedAt * 1000).toLocaleString()}</strong> · batch <code>{entry.batchId}</code>{entry.predecessorBatchId && <> · follows <code>{entry.predecessorBatchId}</code></>} · {entry.lineageState.replaceAll("_", " ")} · {entry.batchState.replaceAll("_", " ")}.
        <p>Tasks (current recorded status): {entry.taskIds.map((taskId, index) => <span key={taskId}>{index > 0 ? "; " : ""}<a href={`#${erpWorkOrderAnchorId(history.projectId, taskId)}`}>{entry.taskTitles[index] ?? taskId}</a> ({entry.taskStatuses[index]?.replaceAll("_", " ") ?? "UNKNOWN"})</span>)}. Frozen review identity: {entry.reviewedResourceKind ?? "UNKNOWN kind"} / <code>{entry.reviewedResourceKey ?? "UNKNOWN resource"}</code>. Source scope {entry.sourceScopeReview.replaceAll("_", " ")}: reviewed {entry.reviewedSourceScope ? entry.reviewedSourceScope.kind === "CHARACTER" ? entry.reviewedSourceScope.identityKey : entry.reviewedSourceScope.kind === "SHARED_OWNER" ? entry.reviewedSourceScope.ownerKey : "UNSCOPED" : "UNKNOWN"}, current {entry.currentSourceScope.kind === "CHARACTER" ? entry.currentSourceScope.identityKey : entry.currentSourceScope.kind === "SHARED_OWNER" ? entry.currentSourceScope.ownerKey : "UNSCOPED"}. Frozen review evidence: {entry.reviewedEvidenceState?.replaceAll("_", " ") ?? "UNKNOWN"}, {entry.reviewedFreshness ?? "UNKNOWN"} freshness, quantity {entry.reviewedQuantity ?? "UNKNOWN"}{entry.reviewedObservedAt !== undefined ? `, observed ${new Date(entry.reviewedObservedAt * 1000).toLocaleString()}` : ", timestamp UNKNOWN"}. Current evidence: {entry.currentEvidenceState.replaceAll("_", " ")}, {entry.currentFreshness} freshness{entry.currentQuantity !== undefined ? `, ${entry.currentQuantity} observed` : ", quantity UNKNOWN"}{entry.currentObservedAt !== undefined ? ` at ${new Date(entry.currentObservedAt * 1000).toLocaleString()}` : ", timestamp UNKNOWN"}. Evidence review {entry.evidenceReview.replaceAll("_", " ")}; interval review {entry.interveningEvidenceReview.replaceAll("_", " ")}; active reservation intent {entry.activeReservationQuantity}. Action cause: UNKNOWN.</p>
        {(() => { const interval = review.savedPlanningBatches.find((candidate) => candidate.stableId === entry.batchId)?.steps.find((step) => step.projectId === history.projectId && step.needId === history.needId)?.observationInterval; return interval && <section aria-label={`Imported evidence since ${history.needLabel} review`} data-testid={`erp-history-interval-${encodeURIComponent(entry.batchId)}-${encodeURIComponent(history.needId)}`}><strong>Intervening imports (each section shows its own review timing):</strong> {interval.state.replaceAll("_", " ")}. {interval.quantityReview === "OBSERVED_VARIATION" && <p>Comparable observations show quantity variation in {interval.observedVariations.length} section comparison{interval.observedVariations.length === 1 ? "" : "s"}: {interval.observedVariations.map((change, index) => <span key={`${change.section}:${change.previousObservedAt}:${change.currentObservedAt}`}>{index ? "; " : ""}{change.section} changed from {change.previousQuantity} at {new Date(change.previousObservedAt * 1000).toLocaleString()} to {change.currentQuantity} at {new Date(change.currentObservedAt * 1000).toLocaleString()}</span>)}. This calls for player review; it does not explain the cause or establish a completed task.</p>} {!interval.points.length ? <p>{interval.state === "INTERVAL_UNAVAILABLE" ? "A per-import timeline is not available for this resource type or selected source. Current evidence remains as shown above." : interval.state === "IDENTITY_CONFLICT" ? "The saved resource or source identity conflicts with the current requirement, so no interval is compared." : interval.state === "SOURCE_SCOPE_UNKNOWN" ? "This older plan did not freeze its exact source character or storage owner, so later snapshots cannot be safely compared with it." : "No retained same-source import falls after this saved review. This does not establish that the resource stayed unchanged."}</p> : <ol>{interval.points.map((point) => <li key={point.snapshotId}>Import #{point.snapshotId} · {new Date((point.generatedAt ?? point.importedAt) * 1000).toLocaleString()}{point.sourceOwnerKey ? ` · owner ${point.sourceOwnerKey}` : ""} {point.sections.map((section) => <span key={section.section}> · {section.section}: {section.state.replaceAll("_", " ")}{section.quantity !== undefined ? ` ${section.quantity}` : section.lowerBound !== undefined ? ` at least ${section.lowerBound}` : " quantity UNKNOWN"}{section.unquantifiedMatchingRows ? `, ${section.unquantifiedMatchingRows} matching rows unquantified` : ""}{section.observedAt !== undefined ? `, observed ${new Date(section.observedAt * 1000).toLocaleString()}` : ""} ({section.relativeToReview.replaceAll("_", " ")})</span>)}</li>)}</ol>}<small>Imports describe resource evidence only; the action cause remains UNKNOWN. Partial sections are lower bounds.{interval.omittedEarlierPointCount ? ` ${interval.omittedEarlierPointCount} intervening samples were omitted by the display cap.` : ""}</small></section>; })()}
        {onPlanHistoryEntry && (() => { const batch = review.savedPlanningBatches.find((candidate) => candidate.stableId === entry.batchId); const blocker = requirementReviewBlocker(batch, history.projectId, history.needId); return blocker ? <small data-testid={`erp-history-review-blocked-${encodeURIComponent(entry.batchId)}-${encodeURIComponent(history.needId)}`}>Resolution draft unavailable: {blocker}</small> : <button type="button" disabled={busy} data-testid={`erp-history-review-${encodeURIComponent(entry.batchId)}-${encodeURIComponent(history.needId)}`} onClick={() => onPlanHistoryEntry(history, entry)}>Review this requirement from this saved generation</button>; })()}
      </li>)}</ol>
      <p>Saved batches in this requirement history: {history.batchIds.map((id) => <code key={id}>{id} </code>)}. Planning lineage and recorded status do not establish task execution, movement, delivery, or completion.</p>
    </li>)}</ol>}
    {review.savedNeedHistoriesTruncated && <p role="note">Requirement history is capped or some saved batches are outside the returned history window; narrow the version/project view before treating this list as complete.</p>}
    <h3>Player-authored dependency packages</h3>
    <p>These sequences follow prerequisites the player linked across projects. Steps are ordered by those links; this does not select a crafting, purchase, or transfer route or claim any task was performed.</p>
    <p>{review.totalPackageCount} package{review.totalPackageCount === 1 ? "" : "s"} · {review.totalStepCount} linked requirement steps · {review.stepsNeedingReview} step{review.stepsNeedingReview === 1 ? "" : "s"} need review.</p>
    {!review.packages.length ? <p>No cross-project fulfillment packages have been linked for this version.</p> : <ol>
      {review.packages.map((item) => <li key={item.stableId}>
        <article>
          <h3>Player-authored package · {item.steps.length} steps</h3>
          {item.cycleDetected && <p role="alert">A cycle was found in stored package links. Review the saved links before using their order.</p>}
          <ol>{item.steps.map((step, index) => <li key={`${step.projectId}/${step.needId}`}>
            <h4>{index + 1}. {step.projectTitle}: {step.needLabel}</h4>
            <p><code>{step.resourceKey}</code> · requires {step.requiredQuantity ?? "UNKNOWN"} · evidence {step.evidenceState.replaceAll("_", " ")} · {step.freshness} freshness{step.observedQuantity !== undefined ? ` · ${step.observedQuantity} observed` : " · quantity UNKNOWN"}{step.observedAt !== undefined ? ` · seen ${new Date(step.observedAt * 1000).toLocaleString()}` : " · timestamp UNKNOWN"}</p>
            <p>Planned source: {step.sourceIdentityKey ? characterName(step.sourceIdentityKey) : step.sourceOwnerKey ? `explicit owner ${step.sourceOwnerKey}` : "UNKNOWN"} · intended recipient: {step.destinationIdentityKey ? characterName(step.destinationIdentityKey) : "unassigned"} · this project’s reservation intent: {step.projectReservationIntentQuantity ?? "UNKNOWN"} · same-source resource commitments across projects: {step.reservationAssessment ? `${step.reservationAssessment.activeQuantity} (${step.reservationAssessment.state.replaceAll("_", " ")})` : "UNKNOWN"}</p>
            {step.reservationAssessment && <p>{step.reservationAssessment.reason} These are recorded commitments, not observed free stock or availability.</p>}
            {step.prerequisiteNeedIds.length > 0 && <p>Waits on: {step.prerequisiteNeedIds.map((dependency) => `${dependency.projectId}/${dependency.needId}`).join(", ")}</p>}
            <p><strong>Prerequisite evidence gate:</strong> {prerequisiteGateLabel(step.prerequisiteGate.state)}{step.prerequisiteGate.blockers.length > 0 && <> Review: {step.prerequisiteGate.blockers.map((blocker) => <span key={`${blocker.projectId}/${blocker.needId}`}> <a href={`#${erpNeedAnchorId(blocker.projectId, blocker.needId)}`}>{blocker.projectId}/{blocker.needId}</a> ({blocker.evidenceState.replaceAll("_", " ")}, {blocker.freshness}{blocker.reservationState ? `, reservations ${blocker.reservationState.replaceAll("_", " ")}` : ""}). {blocker.reason}</span>)}</>}</p>
            {step.workOrders.length ? <ul aria-label={`Manual work for ${step.needLabel}`}>{step.workOrders.map((order) => <li key={order.stableId}><a href={`#${erpNeedAnchorId(step.projectId, step.needId)}`}>{order.title}</a> · recorded status {order.status.replaceAll("_", " ")} · readiness {order.readinessState.replaceAll("_", " ")}{order.progressState ? ` · reconciliation ${order.progressState.replaceAll("_", " ")}` : ""}</li>)}</ul> : <p>No linked manual work order is recorded for this requirement.</p>}
            <p>{step.reason}</p>
            {step.fulfillmentPathways && <section aria-label={`Fulfillment pathways in package for ${step.needLabel}`} data-testid={`erp-package-pathways-${step.projectId}-${step.needId}`}>
              <strong>Current evidence pathways: {step.fulfillmentPathways.state.replaceAll("_", " ")}</strong>
              <p>{step.fulfillmentPathways.reason}</p>
              {step.fulfillmentPathways.options.length ? <ul>{step.fulfillmentPathways.options.map((option, optionIndex) => <li key={`${option.kind}:${optionIndex}`}>
                <span>{option.kind.replaceAll("_", " ")} · {option.provenance}: {option.reason}</span>
                {option.workOrderIds?.length ? <span> Linked manual work: {option.workOrderIds.join(", ")}.</span> : null}
                {option.observedLocation ? <span> Observed {option.observedLocation.quantity} in {option.observedLocation.section}{option.observedLocation.itemRef ? ` (${option.observedLocation.itemRef})` : ""} at {new Date(option.observedLocation.observedAt * 1000).toLocaleString()}.</span> : null}
                {option.candidateLocations?.length ? <ul>{option.candidateLocations.map((location) => <li key={location.characterKey}>{location.characterName} · {location.realm} · identity <code>{location.characterKey}</code> · {location.provenance}, {location.freshness}{location.observedAt !== undefined ? ` · ${new Date(location.observedAt * 1000).toLocaleString()}` : " · timestamp UNKNOWN"}. Location lead only; ownership, access, and route remain UNKNOWN.</li>)}</ul> : null}
                {onPlanNeed && step.projectStatus === "ACTIVE" && step.workOrders.every((order) => order.status === "COMPLETED" || order.status === "CANCELLED") && ["REVIEW_PERSONAL_BANK_RETRIEVAL", "INVESTIGATE_OTHER_CHARACTER_LOCATION", "CHOOSE_MANUAL_SUPPLY_PLAN", "REFRESH_OR_CLARIFY_EVIDENCE"].includes(option.kind) && <button type="button" disabled={busy} onClick={() => onPlanNeed(step.projectId, step.needId, option.kind as ErpSourceFulfillmentReview["sources"][number]["needs"][number]["fulfillmentPathways"]["options"][number]["kind"])}>Plan this manual review</button>}
              </li>)}</ul> : <p>No pathway can be supported by the recorded evidence.</p>}
              <small>These are evidence-qualified review options, not selected routes or completion claims.</small>
            </section>}
            <a href={`#${erpNeedAnchorId(step.projectId, step.needId)}`}>Open this project requirement</a>
          </li>)}</ol>
          {item.nextReviewStepId && (() => { const next = item.steps.find((step) => `${step.projectId}/${step.needId}` === item.nextReviewStepId); const openOrder = next?.workOrders.find((order) => order.status !== "COMPLETED" && order.status !== "CANCELLED"); return <p><strong>Next player review:</strong> {next ? openOrder ? <><a href={`#${erpWorkOrderAnchorId(next.projectId, openOrder.stableId)}`}>Review {next.projectTitle}: {openOrder.title}</a> · {openOrder.status.replaceAll("_", " ")} · {next.evidenceState.replaceAll("_", " ")} evidence. New observations do not confirm this task or its cause.</> : <><a href={`#${erpNeedAnchorId(next.projectId, next.needId)}`}>Review {next.projectTitle}: {next.needLabel}</a> · {next.evidenceState.replaceAll("_", " ")} · {next.freshness} freshness</> : item.nextReviewStepId}</p>; })()}
        </article>
      </li>)}
    </ol>}
    {review.truncated && <p>Showing {review.returnedPackageCount} of {review.totalPackageCount} packages. Narrow the version's project list to review all packages.</p>}
    {review.pathwayReviewTruncated && <p role="note">The shared source review is capped; some package steps may omit pathway details. Open the full source review before treating an absent pathway as unavailable.</p>}
    <small>Observed resource changes remain non-causal. Reservations and work orders describe saved intent, not possession, free stock, availability, or execution.</small>
  </section>;
}
